# Generated by Django 5.0.6 on 2024-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_reviews_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='categoryType',
            field=models.CharField(choices=[('AT', 'Принято'), ('RT', 'Отклонено')], default='RT', max_length=2),
        ),
    ]
