# Generated by Django 5.0.6 on 2024-08-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_reviews_categorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='categoryType',
            field=models.CharField(choices=[('AG', 'Согласование'), ('AT', 'Принято'), ('RT', 'Отклонено')], default='AG', max_length=2),
        ),
    ]
